export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';
export const SET_ERRORS = 'SET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const INPUT_CHANGE = 'INPUT_CHANGE';
export const SET_DATA = 'SET_DATA';
export const FORM_INPUT_CHANGE = 'FORM_INPUT_CHANGE';
export const ADD_USER = 'ADD_USER';
